### ISSUE TITLE
Requesting for the implementation

### ISSUE THREAD

**Issue by harsha-miryala** [smorad/minix-sched#1]
Hey,this is harsha.I am looking to make a similar project to yours. Can you help me with the implementation part.

**Comment by smorad** [comment]
Take a look at `schedule.c` lines `347-410` for the implementation. What specifically are you stuck on?

**Comment by harsha-miryala** [comment]
Like i dont know how to change the code in the OS ... i have understood the code and presently have installed the 3.1.8 version in virtualbox.. after  that how to implement it ??

**Comment by smorad** [comment]
You can either edit the code by hand using an editor inside the OS, or you can use a virtual disk in VirtualBox. Depending on the version of MINIX you may also be able to use the VirtualBox  virtual network to scp files in.

**Comment by harsha-miryala** [comment]
Can you help with any documentation or videos regarding that?

**Comment by smorad** [comment]
https://www.youtube.com/watch?v=oiCiHZXJcR0

**Comment by harsha-miryala** [comment]
Thanks :smiley:
